version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: regex-validator-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: regex-validator-redis
    restart: always
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: regex-validator-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: regex-validator-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: regex-validator-backend
    restart: always
    depends_on:
      - mongodb
      - redis
      - kafka
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/regex-validator
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKER=kafka:9092
      - REGEX_PATTERN=^[a-zA-Z0-9]+$
      - PROCESSING_DELAY_MS=3000
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: regex-validator-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=/api
      - REACT_APP_SOCKET_URL=/
    ports:
      - "3001:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: